language: php

php:
  - 7.1

env:
  global:
    - setup=basic

sudo: false

services:
  - mysql

before_install:
  - travis_retry composer self-update
  - mysql -e "create database IF NOT EXISTS mazedlx_net;" -uroot

before_script:
    - mkdir /home/travis/build/mazedlx/minifig/storage/app/public/images
    - chmod 777 /home/travis/build/mazedlx/minifig/storage/app/public/images
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan migrate:fresh

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
