language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

sudo: false

services:
  - mysql

before_install:
  - travis_retry composer self-update
  - mysql -e "create database IF NOT EXISTS lego_mazedlx_net;" -uroot
  - cp .env.travis .env
  - php artisan key:generate

before_script:
    - php artisan migrate

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
